now:
	python3 mytimer.py
	python3  mytimer_pep8.py

pep8:
	pep8 mytimer_pep8.py

old:
	python3 mytimer_start.py

lec12:
	python3 driver.dog.py
	pep8 dog.py

test:
	make p8
	make v9

p8:
	python3 count.the.p8.py

v9:
	python3 count.the.v09.py

v12:
	python3 count.the.v12.py data.v1

ws2:
	make lec13ws2

lec13ws2:
#	python3 count.the.v12.py data.v1
	python3 count.the.v12.ws2.py data.v1
	
push:
	git commit -a
	git push
