mp = float(input( "MP (/100)"))
print(mp)
we = float(input( "WE (/100)"))
print(we)
assn = float(input( "assn (/100)"))
print(assn)
mt = float(input( "mt (/100)"))
print(mt)
final = float(input( "final (/100)"))
print(final)

mark = ( mp * 0.05 )
# mark = mark + ( we * 0.25 )
mark += ( we * 0.25 )
mark += ( assn * 0.3 )
mark += ( mt * 0.1 )
mark += ( final * 0.3 )
print(mark)
