all:
	python3 lec02.p01.py
	python3 lec03.p02.py
	python3 lec02.p08.py

t1:
	python3 lec02.p01.py

style:
	python3 ../Style/stylecheck.py lec02.p01.py
	python3 ../Style/stylecheck.py lec03.p02.py
	python3 ../Style/stylecheck.py lec02.p08.py

