now:
	python3 vstore.v1.py
	python3 vstore.v2.py
	python3 vstore.v3.py

p01:
	python3 vstore.v3.py
	python3 lec14.p01.py

p02:
	python3 vstore.v1.py
	python3 lec14.p02.py

lec15p01:
	python3 ooclassifierbasev3.py helpdata.v1
	python3 ooclassifierbasev3.py helpdata.testp01
	# python3 ooclassifierbasev3.py helpdata.p01

lec15p02:
	python3 ooclassifierbasev3.py helpdata.v1
	python3 ooclassifierbasev3.py helpdata.testp02
	# python3 ooclassifierbasev3.py helpdata.p02

lec15p03:
	python3 ooclassifierbasev3.py helpdata.v1
	python3 ooclassifierbasev3.py helpdata.testp03
	# python3 ooclassifierbasev3.py helpdata.p03

base:
	python3 ooclassifierbase.py helpdata.v1

slide133:
	python3 ooclassifierbase.py data.v1

slide137:
	python3 ooclassifierbasev2.py data.v1

slide138:
	python3 ooclassifierbasev2.py header.v1 data.v1.noheader

slide139:
	python3 ooclassifierbasev2.py helpdata.v1

slide145:
	python3 ooclassifierbasev3.py data.v1

slide146:
	python3 ooclassifierbasev3.py header.v1 data.v1.noheader

slide147:
	python3 ooclassifierbasev3.py helpdata.v1
