now:
	python3 read.p1.py

test:
	@echo "**********************"
	python3 lec22.p1.bitio.read.py
	@echo "**********************"
	python3 lec22.p2.bitio.read.py
	@echo "**********************"
	python3 lec22.p1.bitio.write.py
	cat message.txt
	@echo "\n**********************"
	python3 lec22.p2.bitio.write.py
	cat message.txt
	@echo "\n**********************"
	python3 lec22.p3.bitio.write.py
	cat message2.txt
	@echo "**********************"

clean:
	-rm mess*txt
