now:
	python3 mp.dt.v1.py

all:
	python3 mp.dt.v1.py
	python3 mp.dt.v2.py
	python3 mp.dt.v3.py
	python3 mp.dt.v4.py
	python3 mp.ft.py

p8:
	python3 count.the.p8.py

v9:
	python3 count.the.v09.py

push:
	git commit -a
	git push
